In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

In [31]:
m = np.matrix([[1,1,1],[1,2,4],[1,3,9],[1,4,16]])
y= np.matrix([[2],[5],[13],[20]])
y

matrix([[ 2],
        [ 5],
        [13],
        [20]])

In [32]:
mtm = m.T@m
mty = m.T*y

In [33]:
np.linalg.inv(mtm)*mty

matrix([[-0.5],
        [ 1.2],
        [ 1. ]])

In [60]:
df_new = None
df=None

In [61]:
df_new =pd.DataFrame(columns=['Name','A','G','S'], data = [['Fuad','20','85','M'],['Fuad','20','85','M'], ['Hassan','20','2.2','M']])

In [62]:
df = pd.DataFrame({'Name':['Fuad Hassan'],'A':[12],'G':[85],'S':['M']})

In [63]:
df

          Name   A   G  S
0  Fuad Hassan  12  85  M

In [64]:
df = pd.concat([df,df_new],ignore_index=True)

In [65]:
df_new

     Name   A    G  S
0    Fuad  20   85  M
1    Fuad  20   85  M
2  Hassan  20  2.2  M

In [68]:
df.drop_duplicates()

          Name   A    G  S
0  Fuad Hassan  12   85  M
1         Fuad  20   85  M
3       Hassan  20  2.2  M

In [73]:
type(df['Name'])

pandas.Series

In [76]:
type(df[['Name']])

pandas.DataFrame